"""Initial migration

Revision ID: 0001
Revises:
Create Date: 2022-01-17 14:38:28.575068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hello_world",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hello_world")
    # ### end Alembic commands ###
